properties:
  csvQuoteSN: true
  header:
    - CodArticolo
    - CodEan
    - Descraarticolo
    - unitamisura
    - unitamisura2
    - unitamisuraSec
    - Coefficiente
    - Costo
    - Prezzo
    - CodiceIva
    - Classea1
    - Classea2
    - Classea3
    - Classea4
    - Classea5
    - qtaPerConf
    - Peso
    - quantitauser01
    - quantitauser02
    - quantitauser03
    - quantitauser04
    - quantitauser05
    - campouser1
    - campouser2
    - campouser3
    - campouser4
    - campouser5
  fornitorimapper:
    atlas:
      codice: CodArticolo
      articolo: CodEan
      descrizione: Descraarticolo
      prezzi: Prezzo
      scatola: unitamisura
    mirage:
      codice: codArticolo
      art: codEan
      descrizioni: descraarticolo
      prezzo: prezzo
      um: unitamisura
    flaminia:
      itemcode: CodArticolo
      EAN: CodEan
      DESCRIPTION: Descraarticolo
      EURO: Prezzo
    chaffoteaux:
      CODICE PRODOTTO: CodArticolo
      DESCRIZIONE PRODOTTO: Descraarticolo
      Listino 07.2021: Prezzo
  input_dir: "C:\\Workspace\\processore_listini\\listini\\input"
  output_dir: "C:\\Workspace\\processore_listini\\listini\\output"