logging:
  level:
    root: ERROR
  file:
    name: ./logs/importatoreListini.log
properties:
  csvQuoteSN: false
  input_dir: "C:\\Workspace\\processore_listini\\listini\\input"
  output_dir: "C:\\Workspace\\processore_listini\\listini\\output"
  imported_dir: "C:\\Workspace\\processore_listini\\listini\\importati"
  header:
    - CodArticolo
    - CodEan
    - Descraarticolo
    - unitamisura
    - unitamisura2
    - unitamisuraSec
    - Coefficiente
    - Costo
    - Prezzo
    - CodiceIva
    - Classea1
    - Classea2
    - Classea3
    - Classea4
    - Classea5
    - qtaPerConf
    - Peso
    - quantitauser01
    - quantitauser02
    - quantitauser03
    - quantitauser04
    - quantitauser05
    - campouser1
    - campouser2
    - campouser3
    - campouser4
    - campouser5
  fornitorimapper:
    atlas:
      CodArticolo: CodArticolo
      CodEan: CodEan
      Descraarticolo: Descraarticolo
      quantitauser01: quantitauser01
      scatola: unitamisura
      aumento_perc: 100
    mirage:
      codice: codArticolo
      art: codEan
      descrizione: descraarticolo
      prezzi: prezzo
      um: unitamisura
      aumento_perc:
    flaminia:
      itemcode: CodArticolo
      EAN: CodEan
      DESCRIPTION: Descraarticolo
      EURO: Prezzo
    chaffoteaux:
      CODICE PRODOTTO: CodArticolo
      DESCRIZIONE PRODOTTO: Descraarticolo
      Listino 07.2021: Prezzo
      aumento_perc: 10